# PPO Configuration for Robot Cleaning Task

# Algorithm Parameters
algorithm:
  name: PPO
  policy: MlpPolicy
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  verbose: 1

# Environment Parameters
environment:
  name: CleaningEnv
  max_episode_steps: 1000
  reward_threshold: 1000.0

# Training Parameters
training:
  total_timesteps: 1000000
  log_interval: 10
  save_path: trained_models/ppo_cleaning_robot

# Evaluation Parameters
evaluation:
  num_episodes: 10
  render: true